development: &defaults
  adapter: mysql2
  encoding: utf8
  database: connectedcity_dev
  password: password
  pool: 32
  username: root
  host: db
  port: 3306

test: &test
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  # from our rds instance:
  pool: 32
