host: connectedcity.com
db_host: 127.0.0.1

# Please set the following secrets in settings.local.yml:
#
# secret_key_base: 
#   Generate: rake secret
##
# db_password:
#   Obtain from our password store.
