class CreateCategories < ActiveRecord::Migration[7.0]
  def up
    create_table :categories do |t|
      t.string :name
      t.integer :parent_id
 
      t.timestamps
    end

    CATEGORIES.each do |k, v|
      Category.create(name: k)
      puts k
      puts '------'
      puts v
      v.each do |k1, v1|
        parent_category_1 = Category.find_by_name(k)
        Category.create(name: k1, parent_id: parent_category_1.id)
        v1.each do |v2|
          parent_category_2 = Category.find_by_name(k1)
          Category.create(name: v2, parent_id: parent_category_2.id)
        end
      end
    end
  end

  def down
    drop_table :categories
  end

  CATEGORIES = {"Women Clothes"=>
    {"Tops"=>["Shirts", "Polo Shirts", "T-Shirts", "Tanks"],
     "Sweaters"=>[],
     "Hoodies & Sweatshirts"=>["Hoodies", "Sweatshirts"],
     "Pants & Leggings"=>["Leggings & Treggings", "Pants"],
     "Shorts"=>[],
     "Skirts"=>[],
     "Jeans"=>[],
     "Dresses"=>[],
     "Wedding Dresses"=>[],
     "Jumpsuits, Playsuits & Overalls"=>["Jumpsuits", "Playsuits", "Overalls"],
     "Jackets, Coats & Vests"=>["Winter Jackets & Coats", "Jackets", "Vests"],
     "Cardigans"=>[],
     "Sets"=>[],
     "Lingerie & Underwear"=>
      ["Underwear Sets",
       "Bras",
       "Panties",
       "Thermal Innerwear",
       "Bra Accessories",
       "Shapewear",
       "Safety Pants",
       "Sexy Lingerie"],
     "Sleepwear & Pajamas"=>["Pajamas", "Night Dresses", "Kimonos & Robes"],
     "Maternity Wear"=>
      ["Nursing Bras",
       "Maternity Dresses",
       "Maternity Tops",
       "Breastfeeding Wear",
       "Maternity Sets",
       "Maternity Bottoms"],
     "Traditional Wear"=>
      ["Traditional Tops", "Traditional Bottoms", "Traditional Sets"],
     "Costumes"=>[],
     "Fabric"=>
      ["Cotton",
       "Wool",
       "Velvet, Silk & Satin",
       "Leather",
       "Vinyl & Nylon",
       "Denim",
       "Canvas"],
     "Socks & Stockings"=>["Socks", "Pantyhose"],
     "Others (Women Clothes)"=>[],
     "Sweaters "=>[],
     "Suits"=>
      ["Suit Sets",
       "Suit Jackets & Blazers",
       "Suit Pants",
       "Suit Vests & Waistcoats"],
     "Pants  "=>["Cargo Pants", "Joggers", "Pants"],
     "Innerwear & Underwear"=>["Underwear", "Undershirts", "Thermal Innerwear"],
     "Sleepwear"=>[],
     "Occupational Attire"=>[],
     "Socks"=>[],
     "Others (Mens Clothes)"=>[]},
   "Beauty"=>
    {"Hand Care"=>["Hand Masks", "Lotion, Cream & Scrubs", "Hand Washes"],
     "Foot Care"=>["Foot Deodorant", "Foot Masks", "Lotion, Cream & Scrubs"],
     "Nail Care"=>
      ["Base & Top Coat",
       "Nail Polish",
       "Nail Polish Remover",
       "Nail Treatment",
       "Artificial Nail",
       "Nail Art & Sticker",
       "Manicure Tools & Devices"],
     "Hair Care"=>
      ["Shampoo",
       "Hair Colour",
       "Hair Treatment",
       "Hair and Scalp Conditioner",
       "Hair Styling"],
     "Men's Care"=>
      ["Bath & Body Care", "Skincare", "Shaving & Grooming", "Hair Care"],
     "Perfumes & Fragrances"=>[],
     "Makeup"=>
      ["Makeup Base & Primer",
       "Foundation",
       "BB & CC Cream",
       "Powder",
       "Concealer & Corrector",
       "Bronzer,Contour & Highlighter",
       "Setting & Finishing Spray",
       "Blush",
       "Eyeshadow",
       "Eye Primer",
       "Eyeliner",
       "Mascara",
       "Eyebrows",
       "Lipstick",
       "Lip Gloss",
       "Lip Liner",
       "Lip Tint & Stain",
       "Lip Plumper",
       "Makeup Removers"],
     "Beauty Tools"=>
      ["Cotton Pads and Buds",
       "Makeup Bags & Organizers",
       "Mirrors",
       "Makeup Brush Cleaners",
       "Makeup Brushes",
       "Sponges & Applicators",
       "Eyelash Curlers",
       "Eyebrow Templates",
       "False Eyelashes",
       "Eyelid Tape & Glue",
       "Pencil Sharpeners",
       "Facial Care Tools",
       "Body Slimming Tools",
       "Hair Removal Tools",
       "Brushes & Combs",
       "Hair Dryers",
       "Hair Styling Tools"],
     "Skincare"=>
      ["Facial Serum & Essence",
       "Face Scrub & Peel",
       "Face Mask & Packs",
       "Eye Treatment",
       "Lip Treatment",
       "Face Sunscreen",
       "After Sun Face Care",
       "Blotting Paper",
       "Acne Treatment"],
     "Beauty Sets & Packages"=>[],
     "Bath & Body Care"=>
      ["Body Wash & Soap",
       "Body Scrub & Peel",
       "Body Masks",
       "Body Oil",
       "Body Cream, Lotion & Butter",
       "Body Deodorants",
       "Massage Oil",
       "Hair Removal Cream & Wax",
       "Body Sunscreen & After Sun",
       "Tanning Oil & Self Tanners",
       "Breast Care"]},
   "Health"=>
    {"Food Supplement"=>
      ["Weight Management Supplements",
       "Beauty Supplements",
       "Fitness Supplements",
       "Well-being Supplements"],
     "Medical Supplies"=>
      ["Blood Pressure Monitors",
       "Blood Glucose Monitors",
       "Pulse Oximeters",
       "Thermometers",
       "Scale & Body Fat Analyzers",
       "Nasal Care",
       "Plasters & Bandages",
       "First Aid Accessories",
       "Ointments & Creams",
       "Medical Antiseptics & Disinfectants",
       "Stethoscopes",
       "Laboratory Tools",
       "Medical Gloves & Masks",
       "Walking Aids",
       "Wheelchairs",
       "Braces & Supports",
       "Hearing Aids"],
     "Personal Care"=>
      ["Hand Sanitizers",
       "Contact lens",
       "Lens Solutions & Eyedrops",
       "Ear Care",
       "Toothbrushes & Accessories",
       "Toothpastes",
       "Dental Floss",
       "Mouth Wash",
       "Denture Care",
       "Teeth Whitening",
       "Orthodontic Accessories",
       "Adult Diapers & Incontinence",
       "Feminine Care",
       "Massage & Therapy Devices",
       "Insect Repellents"],
     "Sexual Wellness"=>["Condoms", "Lubricants", "Performance Enhancement"],
     "Others (Health)"=>[]},
   "Fashion Accessories"=>
    {"Rings"=>[],
     "Earrings"=>[],
     "Scarves & Shawls"=>[],
     "Gloves"=>[],
     "Hair Accessories"=>
      ["Headbands",
       "Hair Ties, Ribbons & Scrunchies",
       "Hair Clips & Hair Pins",
       "Wigs & Extensions",
       "Headpieces, Tiaras & Flower Crowns"],
     "Bracelets & Bangles"=>[],
     "Anklets"=>[],
     "Hats & Caps"=>[],
     "Necklaces"=>[],
     "Eyewear"=>["Sunglasses", "Frames & Glasses", "Eyewear Cases & Accessories"],
     "Investment Precious Metals"=>
      ["Platinum & K Gold", "Silver", "Diamond", "Precious Stones"],
     "Belts"=>[],
     "Neckties, Bow Ties & Cravats"=>[],
     "Additional Accessories"=>
      ["Brooches & Pins",
       "Patches",
       "Charms, Pendants & Ornaments",
       "Cufflinks",
       "Tattoos",
       "Masks",
       "Handkerchiefs"],
     "Accessories Sets & Packages"=>[],
     "Others (Fashion Accessories)"=>[]},
   "Home Appliances"=>
    {"Projectors & Accessories"=>["Projectors & Projector Screens", "Pointers"],
     "Small Household Appliances"=>
      ["Foot Baths & Spas",
       "Water Flossers",
       "Sewing Machines & Accessories",
       "Telephones",
       "Fax Machines",
       "Irons & Steamers",
       "Air Purifiers",
       "Air Dehumidifiers",
       "Vacuum Cleaners & Floor Care Appliances"],
     "Large Household Appliances"=>
      ["Washing Machines",
       "Laundry Dryers",
       "Water Heaters",
       "Air-Conditioners",
       "Air Coolers & Portable Aircons",
       "Fans",
       "Futon & Shoe Dryers",
       "Heaters"],
     "TVs & Accessories"=>
      ["TVs", "TV Antennas", "TV Boxes & Receivers", "TV Brackets"],
     "Kitchen Appliances"=>
      ["Water Filters, Coolers & Dispensers",
       "Kettles",
       "Wine Fridges",
       "Juicers, Blenders & Soya Bean Machines",
       "Coffee Machines & Accessories",
       "Mixers",
       "Dishwashers",
       "Stoves, Hobs & Gas Regulators",
       "Air Fryers",
       "Deep Fryers",
       "Microwaves",
       "Ovens",
       "Toasters",
       "Food Processors & Meat Grinders",
       "Multi-function Cookers",
       "Pressure Cookers",
       "Slow Cookers & Sous Vide Machines",
       "Rice Cookers",
       "Specialty Cookware",
       "Refrigerators",
       "Freezers",
       "Hoods"],
     "Electrical Circuitry & Parts"=>
      ["Electric Sockets & Extension Cords",
       "Electrical Safety",
       "Doorbells",
       "Switches",
       "House Alarms",
       "Lightning Protection"],
     "Batteries"=>[],
     "Remote Controls"=>[],
     "Others (Home Appliances)"=>[]},
   "Men Shoes"=>
    {"Boots"=>["Fashion Boots", "Rain Boots", "Safety Boots"],
     "Sneakers"=>[],
     "Slip Ons & Mules"=>[],
     "Loafers & Boat Shoes"=>[],
     "Oxfords & Lace-Ups"=>[],
     "Sandals & Flip Flops"=>
      ["Flip Flops", "Sandals", "Indoor Slippers", "Health Slippers"],
     "Shoe Care & Accessories"=>
      ["Shoe Care & Cleaning Tools",
       "Shoe Deodorizers",
       "Shoe Laces",
       "Shoe Horns & Trees",
       "Shoe Insoles"],
     "Others (Men Shoes)"=>[]},
   "Mobile & Gadgets"=>
    {"Sim Cards"=>[],
     "Tablets"=>[],
     "Mobile Phones"=>[],
     "Wearable Devices"=>
      ["Smartwatches & Fitness Trackers", "VR Devices", "GPS Trackers"],
     "Accessories"=>
      ["Selfie Accessories",
       "Mobile Lens",
       "Mobile Flashes & Selfie Lights",
       "USB & Mobile Fans",
       "Stylus",
       "Phone Grips",
       "Phone Straps & Keychains",
       "Memory Cards",
       "Casting Devices",
       "Mobile Pouches",
       "USB & Mobile Lights",
       "Pocket Wifi",
       "Batteries",
       "Powerbanks & Powercases",
       "Wearable Accessories",
       "Screen Protectors",
       "Tablet Cases, Covers, & Skins",
       "Phone Cases, Covers, & Skins",
       "Docks & Stands",
       "Cable Cases, Protectors, & Winders",
       "Travel Adaptors",
       "Mobile Cables & Converters",
       "Chargers"],
     "Walkie Talkies"=>[],
     "Others (Mobile & Gadgets)"=>[]},
   "Travel & Luggage"=>
    {"Luggage"=>[],
     "Travel Bags"=>["Duffel & Weekender Bags", "Foldable Bags", "Drawstring Bags"],
     "Travel Accessories"=>
      ["Passport Holders & Covers",
       "Travel Organizers",
       "Luggage Protectors & Covers",
       "Luggage Tags",
       "Luggage Straps",
       "Luggage Locks",
       "Luggage Scales",
       "Travel Pillows & Eye Covers",
       "Travel Size Bottles & Containers"],
     "Others (Travel & Luggage)"=>[]},
   "Women Bags"=>
    {"Backpacks"=>[],
     "Laptop Bags"=>["Laptop Bags & Cases", "Laptop Sleeves", "Laptop Backpacks"],
     "Clutches & Wristlets"=>[],
     "Waist Bags & Chest Bags"=>[],
     "Tote Bags"=>[],
     "Top-handle Bags"=>[],
     "Crossbody & Shoulder Bags"=>[],
     "Wallets"=>
      ["Card Holders",
       "Coin Holders & Purses",
       "Phone & Key Wallets",
       "Bifold & Trifold Wallets",
       "Long Wallets"],
     "Bag Accessories"=>
      ["Bag Straps",
       "Bag Holders",
       "Charms & Twillies",
       "Bag Organizers",
       "Cleaning & Care Equipment"],
     "Others (Women Bags)"=>[]},
   "Women Shoes"=>
    {"Boots"=>["Rain Boots", "Fashion Boots"],
     "Sneakers"=>[],
     "Flats"=>
      ["Ballet Flats",
       "Loafers & Boat Shoes",
       "Oxfords & Lace-Ups",
       "Slip Ons, Mary Janes & Mules"],
     "Heels"=>[],
     "Wedges"=>[],
     "Flat Sandals & Flip Flops"=>
      ["Flat Sandals", "Flip Flops", "Health Slippers", "Indoor Slippers"],
     "Shoe Care & Accessories"=>
      ["Shoe Deodorizers",
       "Insoles & Heel Liners",
       "Shoe Horns & Trees",
       "Shoe Care & Cleaning Tools",
       "Shoe Laces"],
     "Others (Women Shoes)"=>[]},
   "Men Bags"=>
    {"Backpacks"=>[],
     "Laptop Bags"=>["Laptop Bags & Cases", "Laptop Sleeves", "Laptop Backpacks"],
     "Tote Bags"=>[],
     "Briefcases"=>[],
     "Clutches"=>[],
     "Waist Bags & Chest Bags"=>[],
     "Crossbody & Shoulder Bags"=>[],
     "Wallets"=>
      ["Card Holders",
       "Coin Holders & Purses",
       "Phone & Key Wallets",
       "Bifold & Trifold Wallets",
       "Long Wallets"],
     "Others (Men Bags)"=>[]},
   "Watches"=>
    {"Men Watches"=>[],
     "Set & Couple Watches"=>[],
     "Watches Accessories"=>
      ["Straps", "Service Tools", "Buckles", "Batteries", "Boxes"],
     "Others (Watches)"=>[]},
   "Audio"=>
    {"Earphones, Headphones & Headsets"=>[],
     "Media Players"=>
      ["MP3 & MP4 Players",
       "CD, DVD, & Blu-ray Players",
       "Voice Recorders",
       "Radio & Cassette Players"],
     "Microphones"=>[],
     "Amplifiers & Mixers"=>[],
     "Home Audio & Speakers"=>["Speakers", "Home Theater Systems", "AV Receivers"],
     "Audio & Video Cables & Converters"=>[],
     "Others (Audio)"=>[]},
   "Food & Beverage"=>
    {"Convenience / Ready-to-eat"=>
      ["Cooked Food", "Instant Rice & Porridge", "Instant Hotpot", "Instant Noodles"],
     "Snacks"=>
      ["Sweets & Candies",
       "Chocolate",
       "Biscuits, Cookies & Wafers",
       "Chips & Crisps",
       "Seeds",
       "Popcorn",
       "Seaweed",
       "Nuts",
       "Pudding, Jellies & Marshmallow",
       "Dried Snacks",
       "Meat Jerky",
       "Dried Fruits",
       "Meat Floss",
       "Seafood Snacks"],
     "Food Staples"=>
      ["Beans & Grains",
       "Dried Seafood",
       "Traditional Herbs",
       "Noodles",
       "Rice",
       "Pasta",
       "Others",
       "Preserved Vegetables",
       "Canned Fruits",
       "Canned Meat",
       "Canned Seafood",
       "Canned Vegetables",
       "Canned Soup"],
     "Cooking Essentials"=>
      ["Oil",
       "Seasonings & Condiments",
       "Sugar",
       "Sweetener",
       "Stock, Gravy & Instant Soup",
       "Cooking Paste & Kit",
       "Flavour Enhancers",
       "Flour Coating"],
     "Baking Needs"=>
      ["Baking Flavoring",
       "Baking Powder & Soda",
       "Baking Premix Flour",
       "Flour",
       "Food Coloring",
       "Baking Decoration"],
     "Breakfast Cereals & Spread"=>
      ["Honey & Maple Syrups",
       "Jam & Spread",
       "Cereal, Granola & Oats",
       "Breakfast Bar"],
     "Beverages"=>
      ["Coffee",
       "Tea & Tea Bags",
       "Chocolate Drinks",
       "Energy & Isotonic Drinks",
       "Water",
       "Juice & Juice Vinegar",
       "Cordial & Syrups",
       "Carbonated Drinks & Tonics",
       "Powdered Drink Mixes",
       "Dessert Drink",
       "Traditional & Herbal Drinks",
       "Drink Toppings",
       "Non-dairy Milk"],
     "Dairy & Eggs"=>
      ["Fresh Milk",
       "UHT Milk",
       "Condensed & Evaporated Milk",
       "Powdered Milk",
       "Yogurt & Cultured Milk",
       "Creamers",
       "Butter & Margarine",
       "Cheese & Cheese Powder",
       "Ice cream",
       "Eggs",
       "Beancurd"],
     "Fresh & Frozen Food"=>
      ["Beef",
       "Poultry",
       "Pork",
       "Other Meat",
       "Fish",
       "Seafood  ",
       "Vegetarian Meat",
       "Others",
       "Vegetables",
       "Fruits",
       "Mushroom",
       "Frozen Processed Food",
       "Processed Meat & Seafood"],
     "Bakery"=>["Breads", "Cakes & Pies", "Pastry"],
     "Alcoholic Beverages"=>[],
     "Gift Baskets & Hampers"=>[],
     "Others (Food)"=>[]},
   "Pets"=>
    {"Pet Food"=>
      ["Dog Food",
       "Dog Treats",
       "Cat Food",
       "Cat Treats",
       "Small Pet Food",
       "Small Pet Treats",
       "Aquarium Pet Food",
       "Bird Feed",
       "Reptile Food"],
     "Pet Accessories"=>
      ["Bowls & Feeders",
       "Pet Travel Essentials",
       "Leashes, Collars, Harnesses & Muzzles",
       "Pet Toys",
       "Pet Beds & Mats",
       "Pet Houses",
       "Pet Habitats & Accessories",
       "Cages & Crates",
       "Scratching Pads & Posts",
       "Aquarium Needs"],
     "Litter & Toilet"=>
      ["Cat Litter & Boxes",
       "Small Pet Bedding & Litter",
       "Diapers",
       "Dog Training Pads & Trays",
       "Poop Bags & Scoopers"],
     "Pet Grooming"=>["Hair Care", "Oral Care", "Claw Care"],
     "Pet Clothing & Accessories"=>
      ["Pet Clothing",
       "Wet Weather Gear",
       "Boots, Socks & Paw Protectors",
       "Neck Accessories",
       "Eyewear",
       "Hair Accessories",
       "Hats"],
     "Pet Healthcare"=>[],
     "Others (Pets)"=>[]},
   "Mom & Baby"=>
    {"Baby Travel Essentials"=>
      ["Baby Carrier",
       "Strollers & Travel Systems",
       "Stroller Accessories",
       "Car & Motorbike Seats",
       "Car & Motorbike Seats Accessories",
       "Diaper Bags",
       "Child Harnesses & Leashes"],
     "Feeding Essentials"=>
      ["Bottle-feeding",
       "Breastfeeding",
       "Highchairs & Booster Seats",
       "Baby Feeding Utensils",
       "Bibs",
       "Pacifiers",
       "Food Processors"],
     "Maternity Accessories"=>["Supporting Belts", "Maternity Pillows"],
     "Maternity Healthcare"=>
      ["Maternity Milk", "Maternity Vitamins & Supplement", "Moisturizers & Creams"],
     "Bath & Body Care"=>
      ["Baby Bathing Tubs & Seats",
       "Bath Robes, Towels & Wash Cloths",
       "Baby Shower Caps",
       "Baby Bathing Tools & Accessories",
       "Baby Hair Care & Body Wash",
       "Baby Colognes & Fragrances",
       "Baby Grooming Tools",
       "Baby Wipes",
       "Baby Laundry Detergent"],
     "Nursery"=>
      ["Cribs & Cradles & Beds",
       "Bouncers, Rockers & Jumpers",
       "Walkers",
       "Storage & Organization",
       "Blankets & Wrappers",
       "Pillows & Bolsters",
       "Bedsheets"],
     "Baby Safety"=>
      ["Monitors",
       "Mosquito Netting",
       "Bumpers, Rails & Guards",
       "Edge & Corner Guards",
       "Baby Gates & Doorways",
       "Safety Locks & Straps"],
     "Milk Formula & Baby Food"=>
      ["Milk Formula", "Baby Porridge, Puree & Cereal", "Baby Snack"],
     "Baby Healthcare"=>
      ["Baby Vitamins & Supplements",
       "Baby Nasal Care",
       "Baby Oral Care",
       "Baby Sun Care",
       "Baby Lotion & Creams",
       "Baby Oils",
       "Baby Powders"],
     "Diapering & Potty"=>
      ["Changing Pads & Kits",
       "Potty Training & Commode Chairs",
       "Disposable Diapers",
       "Cloth Diapers & Accessories"],
     "Toys"=>
      ["Playgym & Playmats",
       "Playards & Playpens",
       "Bath Toys",
       "Crib Mobiles & Rattles",
       "Teethers",
       "Block Toys",
       "Dolls & Accessories",
       "Doll Houses & Accessories",
       "Stuffed Toys",
       "Pretend Play",
       "Toy Vehicles",
       "Bicycles, Scooters & Ride-ons",
       "Inflatables & Slides",
       "Play Tents, Tunnels & Ball Pits",
       "Pool, Water & Sand Toys",
       "Blasters & Toy Guns",
       "Sports Toys",
       "Flying Toys, Kites & Wind Spinners",
       "Arts & Crafts",
       "Math Toys",
       "Science & Tech Toys",
       "Shape Sorters",
       "Puzzles",
       "Musical Toys",
       "Toy Tablets & Computers",
       "Robot Toys",
       "Slime & Squishy Toys"],
     "Gift Sets & Packages"=>[],
     "Others (Mom & Baby)"=>[]},
   "Baby & Kids Fashion"=>
    {"Baby Clothes"=>
      ["Regular Outerwear",
       "Winter Outerwear",
       "Dresses",
       "Pants & Leggings",
       "Shorts",
       "Skirts",
       "Sleepwear",
       "Tops",
       "Bodysuits & Jumpsuits",
       "Sets",
       "Swimwear"],
     "Baby Mittens & Footwear"=>[],
     "Baby & Kids Accessories"=>
      ["Baby & Kids Backpacks",
       "Baby & Kids Crossbody & Shoulder Bags",
       "Baby & Kids Trolley Bags",
       "Baby & Kids Wallets",
       "Baby & Kids Hats & Caps",
       "Baby & Kids Eyewear",
       "Baby & Kids Hair Accessories",
       "Baby & Kids Gloves",
       "Baby & Kids Belts",
       "Baby & Kids Socks",
       "Baby & Kids Scarves",
       "Baby & Kids Watches",
       "Baby & Kids Bracelets",
       "Baby & Kids Earrings",
       "Baby & Kids Necklaces",
       "Baby & Kids Rings",
       "Baby & Kids Raincoats",
       "Baby & Kids Rain Boots",
       "Baby & Kids Earmuffs"],
     "Boy Clothes"=>
      ["Boy Costumes",
       "Boy Underwear & Innerwear",
       "Boy Sleepwear",
       "Boy Swimwear",
       "Boy Tops",
       "Boy Outerwear",
       "Boy Bottoms",
       "Boy Suits & Sets"],
     "Girl Clothes"=>
      ["Girl Costumes",
       "Girl Underwear & Innerwear",
       "Girl Sleepwear",
       "Girl Swimwear",
       "Girl Tops",
       "Girl Outerwear",
       "Girl Bottoms",
       "Girl Rompers & Jumpsuits",
       "Girl Dresses",
       "Girl Suits & Sets"],
     "Boy Shoes"=>
      ["Boy Boots",
       "Boy Sandals",
       "Boy Sneakers",
       "Boy Flip Flops",
       "Boy Formal Shoes",
       "Boy Loafers"],
     "Girl Shoes"=>
      ["Girl Boots",
       "Girl Sandals",
       "Girl Sneakers",
       "Girl Loafers",
       "Girl Flip Flops",
       "Girl Flats"],
     "Others (Baby & Kids Fashion)"=>[]},
   "Gaming & Consoles"=>
    {"Console Machines"=>
      ["Playstation",
       "Xbox",
       "Wii",
       "Nintendo DS",
       "Gameboy",
       "Switch",
       "PS Vita",
       "PSP",
       "Other Console Machines"],
     "Console Accessories"=>[],
     "Video Games"=>
      ["Playstation",
       "Xbox",
       "Wii",
       "Nintendo DS",
       "Gameboy",
       "Switch",
       "PS Vita",
       "PSP",
       "PC Game",
       "Other Video Games"],
     "Others (Gaming & Consoles)"=>[]},
   "Cameras & Drones"=>
    {"Cameras"=>
      ["Point & Shoot",
       "Mirrorless Cameras",
       "Action Cameras",
       "Video Camcorders",
       "Instant Cameras",
       "Analog Cameras",
       "DSLRs"],
     "Security Cameras & Systems"=>["CCTV Security Cameras", "DVRs", "Dummy Cameras"],
     "Lenses"=>[],
     "Lens Accessories"=>
      ["Lens Mount & Adaptors", "Lens Caps", "Filters", "Lens Hoods"],
     "Camera Accessories"=>
      ["Flashes",
       "Flash Accessories",
       "Gimbals & Stabilizers",
       "Lighting & Studio Equipments",
       "Photo Films & Papers",
       "Photo Printers",
       "Camera Cases & Bags",
       "Battery Chargers",
       "Batteries & Battery Grips",
       "Tripods, Monopods, & Accessories"],
     "Camera Care"=>
      ["Dry Boxes & Cabinets",
       "Cleaning Kit",
       "Silica Gel",
       "Blowers",
       "Lenspens & Brushes"],
     "Drones"=>[],
     "Drone Accessories"=>[],
     "Others (Cameras & Drones)"=>[]},
   "Home & Living"=>
    {"Home Fragrance & Aromatherapy"=>
      ["Air Fresheners & Home Fragrance",
       "Essential Oils",
       "Diffusers, Humidifiers & Oil Burners"],
     "Bathrooms"=>
      ["Toilet Bowls, Seats & Covers",
       "Toothbrush Holders & Toothpaste Dispensers",
       "Soap Dispensers, Holders & Boxes",
       "Bathroom Racks & Cabinets",
       "Bathtubs",
       "Bath Towels",
       "Face & Hand Towels",
       "Bath Robes",
       "Showerheads & Bidet Sprays",
       "Bath Brushes & Loofahs",
       "Shower Curtains",
       "Shower Seats & Commodes",
       "Safety Handles",
       "Shower Caps"],
     "Bedding"=>
      ["Cooling Mats",
       "Mattress Protectors & Toppers",
       "Blankets, Comforters & Quilts",
       "Pillows",
       "Bedsheets, Pillowcases & Bolster Cases",
       "Matresses",
       "Mosquito Nets",
       "Bolsters"],
     "Decoration"=>
      ["Flowers",
       "Furniture & Appliance Covers",
       "Curtains & Blinds",
       "Photo Frames & Wall Decoration",
       "Wallpapers & Wall Stickers",
       "Clocks",
       "Floor Mats",
       "Carpets & Rugs",
       "Vases & Vessels",
       "Candles & Candleholders",
       "Mirrors",
       "Table Cloths"],
     "Hand Warmers, Hot Water Bags & Ice Bags"=>[],
     "Furniture"=>
      ["Cushions",
       "Doorstoppers",
       "Bed Frames & Headboards",
       "Desks & Tables",
       "Wardrobes",
       "Benches, Chairs & Stools",
       "Sofas",
       "Cupboards & Cabinets",
       "Shelves & Racks"],
     "Gardening"=>
      ["Plants",
       "Garden Decorations",
       "Garden Soils & Growing Media",
       "Fertilizer",
       "Seeds & Bulbs",
       "Pots & Planters",
       "Irrigation Systems",
       "Gardening Tools",
       "Lawn Mowers"],
     "Tools & Home Improvement"=>
      ["Tool Boxes",
       "Measuring Tapes",
       "Spanner Sets",
       "Hammers",
       "Pliers",
       "Nails, Screws & Fasteners",
       "Drills, Screwdrivers & Accessories",
       "Saws, Cut-off Machines & Grinders",
       "Pressure Washers",
       "Power Generators",
       "Electrical Testers & Multimeters",
       "Levels & Measuring Wheels",
       "Rangefinders",
       "Air Compressors",
       "Sandpaper, Power Sanders & Accessories",
       "Power Welding Tools",
       "Blowers",
       "Industrial Adhesives & Tapes",
       "Protective Gloves, Goggles & Masks",
       "Sinks & Water Taps",
       "Roofing & Flooring",
       "Wall Paints & Coatings",
       "Air Pumps, Parts & Accessories",
       "Ladders",
       "Trollies",
       "Shades, Awnings & Tarpaulins",
       "Construction Materials",
       "Doors & Windows"],
     "Home Care Supplies"=>
      ["Clotheslines & Drying Racks",
       "Cleaning Brushes",
       "Brooms",
       "Dusters",
       "Mops",
       "Basins, Buckets & Water Dippers",
       "Sponges & Scouring Pads",
       "Trash & Recycling Bins",
       "Plastic Bags & Trash Bags",
       "Cleaning Cloths",
       "Pest & Weed Control",
       "Tissue & Paper Towels",
       "Toilet Paper",
       "Cleaning Agents",
       "Laundry Care"],
     "Kitchenware"=>
      ["Grills & Accessories",
       "Bakewares & Decorations",
       "Pans",
       "Pots",
       "Food Storage",
       "Cling Wrap",
       "Aluminium Foil",
       "Tea, Coffee & Bartending Equipments",
       "Kitchen Racks",
       "Aprons & Kitchen Gloves",
       "Spatulas & Cooking Tweezers",
       "Chopping Boards",
       "Knives & Kitchen Scissors",
       "Whisks & Beaters",
       "Can & Bottle Openers",
       "Measuring Glasses & Spoons",
       "Strainers",
       "Graters, Peelers & Cutters",
       "Kitchen Weighing Scales",
       "Sealers"],
     "Dinnerware"=>
      ["Jugs, Pitchers & Accessories",
       "Tea Pots & Sets",
       "Cups, Mugs & Glasses",
       "Water Bottles & Accessories",
       "Bowls",
       "Plates",
       "Cutleries",
       "Straws",
       "Food Covers",
       "Placemats & Coasters"],
     "Lighting"=>[],
     "Safety & Security"=>
      ["Safes", "Fire Fighting Equipments", "Door Hardware & Locks"],
     "Home Organizers"=>
      ["Hangers & Pegs",
       "Storage Boxes, Bags & Baskets",
       "Shoe Storage Boxes",
       "Hooks",
       "Laundry Bags & Baskets",
       "Desk Organizers",
       "Wardrobe Organizers",
       "Jewelry Organizers",
       "Tissue Holders"],
     "Party Supplies"=>
      ["Balloons",
       "Wooden Clips",
       "Backdrops & Banners",
       "Cards",
       "Disposable Tableware",
       "Party Hats & Masks",
       "Sashes"],
     "Fengshui & Religious Supplies"=>[],
     "Others ( Home & Living)"=>[]},
   "Sports & Outdoors "=>
    {"Fishing Equipment"=>
      ["Fishing Hooks",
       "Fishing Rods & Reels",
       "Fish Finders",
       "Fishing Lines",
       "Lures & Baits",
       "Fishing Bags",
       "Fishing Nets"],
     "Cycling Equipment"=>
      ["Bicycles", "Bicycle Parts & Accessories", "Cycling Helmets"],
     "Camping & Hiking Equipment"=>
      ["Camping Cookware",
       "Camping Lamps & Flashlights",
       "Tents & Tent Accessories",
       "Sleeping Bags",
       "Binoculars, Monoculars & Telescopes",
       "Compasses",
       "Camping Knives & Survival Kits",
       "Hammocks",
       "Hiking Sticks",
       "Picnic Mats & Baskets"],
     "Rock Climbing Equipment"=>[],
     "Boardsports Equipment"=>
      ["Skateboards & Roller Blades",
       "Scooters & Unicycles",
       "Segways & Hoverboards",
       "Helmets & Protective Gears"],
     "Soccer, Futsal & Sepak Takraw Equipment"=>
      ["Balls", "Goalkeeper Gloves & Shin Guards", "Goal Posts & Nets"],
     "Basketball Equipment"=>["Basket Balls", "Basketball Rings"],
     "Volleyball Equipment"=>["Volley Balls", "Volley Nets"],
     "Badminton Equipment"=>["Badminton Rackets", "Shuttlecocks", "Badminton Nets"],
     "Tennis Equipment"=>["Tennis Rackets", "Tennis Balls", "Tennis Nets"],
     "Table Tennis Equipment"=>
      ["Table Tennis Balls", "Table Tennis Bats", "Table Tennis Nets"],
     "Boxing & Martial Arts Equipment"=>
      ["Punching Bags & Paddings", "Martial Arts Belts", "Gloves, Wraps & Helmets"],
     "Golf Equipment"=>
      ["Golf Balls",
       "Golf Clubs",
       "Gears &Training Equipment",
       "Golf Bags & Organizers"],
     "Baseball & Softball Equipment"=>[],
     "Squash Equipment"=>[],
     "Shooting & Survival Games Equipment"=>[],
     "Rugby Equipment"=>[],
     "Billiards Equipment"=>[],
     "Surfing & Wakeboarding Equipment"=>[],
     "Ice Skating & Winter Sports Equipment"=>[],
     "Swimming & Diving Equipment"=>
      ["Swimming Caps",
       "Swimming Goggles",
       "Swimming Boards",
       "Diving Flashlights",
       "Diving Masks",
       "Flippers",
       "Life Jackets"],
     "Boating Equipment"=>[],
     "Yoga & Pilates Equipment"=>
      ["Yoga Mats", "Yoga Blocks, Rings & Foam Rollers", "Resistance Bands"],
     "Fitness Equipment"=>
      ["Weight Training",
       "Skipping Ropes",
       "Gym Balls",
       "Fitness Machines",
       "Ab Rollers",
       "Pull Up & Push Up Bars"],
     "Darts Equipment"=>[],
     "Sports Footwear"=>
      ["Running Shoes",
       "Training Shoes",
       "Tennis Shoes",
       "Volleyball Shoes",
       "Badminton Shoes",
       "Futsal Shoes",
       "Hiking Shoes",
       "Soccer Shoes",
       "Kid's Sport Shoes"],
     "Sports & Outdoor Apparels"=>
      ["Sets",
       "Jackets",
       "Tops",
       "Jerseys",
       "Bottoms",
       "Sports Bras",
       "Kid's Sports Apparel",
       "Swimming Trunks",
       "Bikini Sets",
       "One-Piece Swimsuits",
       "Rash Guards"],
     "Sports & Outdoor Accessories"=>
      ["Stopwatches & Pedometers",
       "Shoe Bags",
       "Sports Wristbands",
       "Sports Headbands",
       "Sports & Outdoor Hats",
       "Dry Bags",
       "Rain Coats",
       "Umbrellas",
       "Mouthguards & Sport Tapes",
       "Training Equipments",
       "Gym Protective Gears"],
     "Others (Sports & Outdoors)"=>[]},
   "Stationery"=>
    {"Gift & Wrapping"=>
      ["Gift Wrappers",
       "Gift Boxes",
       "Gift Bags",
       "Ribbons",
       "Bubble Wraps",
       "Carton Boxes"],
     "Writing & Correction"=>
      ["Pens & Inks",
       "Pencils",
       "Eraser & Correction Supplies",
       "Markers",
       "Highlighters"],
     "School & Office Equipment"=>
      ["Writing Boards & Board Stands",
       "Calculators",
       "Pen Knives & Paper Cutters",
       "Strings & Tapes",
       "Glues",
       "Label Printers",
       "Lanyards & Name Tags",
       "Clips, Pins & Tacks",
       "Hole Punchers",
       "Scissors",
       "Ink Stamps & Pads",
       "Staplers & Staples",
       "Calendars",
       "Folders, Paper Organizers & Accessories",
       "Rulers, Protractors & Stencils",
       "Sharpeners",
       "Pencil Cases"],
     "Art Supplies"=>
      ["Color Pencils",
       "Crayons & Pastels",
       "Water & Poster Colours",
       "Oil Paint",
       "Acrylic Paint",
       "Paint Brushes",
       "Paint Palettes",
       "Canvases & Easels",
       "Sketch Books"],
     "Notebooks & Papers"=>
      ["Bookmarks",
       "Book Covers",
       "Thermal Paper & Continuous Paper",
       "Printing & Photocopy Paper",
       "Loose Leaf",
       "Memo & Sticky Notes",
       "Art Paper & Boards",
       "Notebooks & Notepads",
       "Labels & Stickers"],
     "Letters & Envelopes"=>
      ["Envelopes & Angpao", "Post Cards", "Postage Stamps & Duty Stamps"],
     "Others (Stationery)"=>[]},
   "Hobbies & Collections"=>
    {"Collectible Items"=>
      ["Action Figurines",
       "Statues & Sculptures",
       "Mecha Models & Diecast",
       "Vehicle Models & Diecast",
       "Idol Collectibles",
       "Sports Collectibles",
       "Anime & Manga Collectibles",
       "Coins & Bank Notes"],
     "Souvenirs"=>["Hand Fans", "Keychains", "Coin Banks", "Fridge Magnets"],
     "Toys & Games"=>
      ["Dice, Board & Card Games",
       "Magic Toys",
       "Prank Toys",
       "Rubik's Cubes",
       "Spinning Tops",
       "Kendamas",
       "Yo-yos",
       "Remote Control Toys & Accessories",
       "Capsule Toys"],
     "CD, DVD & Bluray"=>[],
     "Musical Instruments & Accessories"=>
      ["Keyboards & Pianos",
       "Percussion Instruments",
       "Wind Instruments",
       "Music Accessories",
       "Guitars & Bass Guitars",
       "Ukuleles and Other String Instruments"],
     "Vinyl Records"=>[],
     "Photo Albums"=>[],
     "Needlework"=>[],
     "Others (Hobbies & Collections)"=>[]},
   "Automobiles"=>
    {"Automobiles"=>[],
     "Automobile Interior Accessories"=>
      ["Navigation & AV Receivers",
       "Amplifiers, Speakers & Subwoofers",
       "Organizers & Compartments",
       "Perfumes, Air Fresheners & Purifiers",
       "Carpets & Mats",
       "Seat Headrests & Back Supports",
       "Car Mattresses",
       "Steering Wheels & Covers",
       "Seats & Seat Covers",
       "Phone Holders",
       "USB Chargers, FM & Bluetooth Transmitters",
       "Pedals & Gear Sticks",
       "Sun Shields & Dash Covers",
       "Locks & Security",
       "Camcorders & Parking Cameras",
       "HUD, Speedometers & Gauges"],
     "Automobile Exterior Accessories"=>
      ["Garnish",
       "Antennas",
       "Covers",
       "Stickers, Logos & Emblems",
       "Mud Flaps & Splash Guards",
       "Sill Plates",
       "Gutters",
       "Horns & Accessories",
       "Mirrors & Accessories",
       "License Plate Accessories"],
     "Automobile Spare Parts"=>
      ["Body, Frame & Bumpers",
       "Windshield Wipers & Washers",
       "Exhaust & Emissions",
       "Wheels, Rims & Accessories",
       "Tires & Accessories",
       "Shocks, Struts & Suspension",
       "Radiators, Engine Cooling & Climate Control",
       "Drivetrain, Transmission & Clutches",
       "Bearing & Seals",
       "Pistons",
       "Air Filters",
       "Oil Filters",
       "Brake System",
       "Belts, Hoses & Pulleys",
       "Ignition",
       "Batteries & Accessories",
       "Lighting",
       "Fuel System"],
     "Automotive Tools"=>
      ["Test, Diagnostic & Repair Tools", "Tire Pressure Detectors"],
     "Automotive Care"=>
      ["Wash & Waxes",
       "Glass Care & Water Repellents",
       "Interior Care",
       "Tire & Wheel Care",
       "Polish, Coating & Sealants"],
     "Automotive Oils & Lubes"=>
      ["Oils",
       "Fuel Additives & Savers",
       "Greases & Lubricants",
       "Antifreezes & Coolants",
       "Brake Fluids",
       "Transmissions Fluids"],
     "Automotive Keychains & Key Covers"=>[],
     "Others (Automobiles)"=>[]},
   "Motorcycles"=>
    {"Motorcycles"=>[],
     "Motorcycle Accessories"=>
      ["Carpets",
       "Speedometers, Odometers & Gauges",
       "Covers",
       "Stickers, Logos & Emblems",
       "Seats & Seat Covers",
       "Mirrors & Accessories",
       "Locks & Security",
       "Boxes & Cases",
       "Phone Holders",
       "Mud Flaps & Splash Guards"],
     "Motorcycle Spare Parts"=>
      ["Fuel System",
       "Brake System",
       "Shocks, Struts & Suspension",
       "Chains & Gears",
       "Clutches",
       "Bearings",
       "Batteries & Accessories",
       "Horns & Accessories",
       "Cables & Tubes",
       "Body & Frame",
       "Exhaust & Emissions",
       "Wheels, Rims & Accessories",
       "Tires & Accessories",
       "Lighting"],
     "Motorcycle Helmets & Accessories"=>[],
     "Others ( Motorcycles)"=>[]},
   "Tickets, Vouchers & Services"=>
    {"Events & Attractions"=>
      ["Theme Parks & Attractions",
       "Events, Fairs & Conferences",
       "Movies",
       "Concerts & Exhibitions"],
     "F&B"=>["Dine-in & Takeaway", "Food Delivery"],
     "Shopping"=>["Malls & Department Stores", "Supermarkets"],
     "Utilities"=>[],
     "Services"=>
      ["Housekeeping",
       "Delivery & Moving",
       "Insurance",
       "Air-Conditioning Servicing",
       "Photography & Printing",
       "Design"],
     "Beauty & Wellness"=>["Health", "Dental", "Fitness", "Hair", "Spa & Massage"],
     "Transport"=>[],
     "Lessons & Workshops"=>[],
     "Telco"=>["Internet & Cable TV", "Mobile Data", "Mobile Top-ups & Pre-paid"],
     "Travel"=>
      ["Accommodation",
       "Hot Springs",
       "Flights",
       "Trains",
       "Buses",
       "Car Rentals",
       "Tour & Packages"],
     "Others (Tickets, Vouchers & Services)"=>[]},
   "Books & Magazines"=>
    {"Magazines & Newspaper"=>["Business", "Lifestyle", "Teenager"],
     "Books"=>
      ["Comics & Manga",
       "Children's Books",
       "Agriculture, Forestry & Fishery",
       "Adult's Books",
       "Arts, Design & Photography",
       "Recipes & Cooking",
       "Business & Investment",
       "Politics, Law & Social Sciences",
       "Computers & Technology",
       "Health, Fitness & Dieting",
       "Travel & Tourism",
       "Language Learning & Dictionaries",
       "Hobbies",
       "LGBTQ+ Literature",
       "Light Novels",
       "Classic Literature",
       "Fantasy",
       "Action, Crime & Thrillers",
       "Romance",
       "Biography & Memoirs",
       "Science & Maths",
       "Medical",
       "Parenting & Family",
       "Psychology & Relationships",
       "Religion & Philosophy",
       "History & Cultures",
       "Careers, Self Help & Personal Development",
       "Horoscopes",
       "Education & School",
       "Sticker & Colouring Books",
       "Music",
       "Baby & Soft Books",
       "Audio Books",
       "Others (Books)"],
     "E-Books"=>[],
     "Others (Books & Magazines)"=>[]},
   "Computers & Accessories"=>
    {"Desktop Computers"=>
      ["Desktop PC", "Mini PC", "Server PC", "All-in-One Desktops"],
     "Monitors"=>[],
     "Desktop & Laptop Components"=>
      ["Fans & Heatsinks",
       "Processors",
       "Motherboards",
       "Graphics Cards",
       "Thermal Paste",
       "Power Supply Units",
       "RAM",
       "UPS & Stabilizers",
       "PC Cases",
       "Optical Drives",
       "Sound Cards"],
     "Data Storage"=>
      ["Hard Drives",
       "SSD",
       "Network Attached Storage (NAS)",
       "Flash Drives & OTG",
       "Hard Disk Casings & Dockings",
       "Compact Discs"],
     "Network Components"=>
      ["Modems & Wireless Routers",
       "Repeaters",
       "Wireless Adapters & Network Cards",
       "Powerline Adapters",
       "Network Switches & PoE",
       "Network Cables & Connectors",
       "KVM Switches",
       "Print Servers"],
     "Softwares"=>[],
     "Office Equipment"=>
      ["Typewriters", "Absence Machines", "Paper Shredders", "Money Counters"],
     "Printers & Scanners"=>
      ["Printers, Scanners & Photocopy Machines",
       "Thermal & Barcode Printers",
       "Inks & Toners",
       "3D Printers"],
     "Peripherals & Accessories"=>
      ["USB Hubs & Card Readers",
       "Webcams",
       "Laptop Skins & Covers",
       "Cooling Pads",
       "Laptop Stands & Foldable Laptop Desks",
       "Keyboard & Trackpad Covers",
       "Laptop Batteries",
       "Laptop Chargers & Adaptors",
       "Video Conference Devices",
       "Mouse Pads"],
     "Keyboards & Mice"=>["Computer Mice", "Keyboards", "Drawing Tablets"],
     "Laptops"=>[],
     "Others (Computers & Accessories)"=>[]},
   "Deals"=>{"Scan & Pay Voucher"=>[], "Deals"=>[]}
  }
end
