require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LocationMenusController do

  # This should return the minimal set of attributes required to create a valid
  # LocationMenu. As you add validations to LocationMenu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocationMenusController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all location_menus as @location_menus" do
      location_menu = LocationMenu.create! valid_attributes
      get :index, {}, valid_session
      assigns(:location_menus).should eq([location_menu])
    end
  end

  describe "GET show" do
    it "assigns the requested location_menu as @location_menu" do
      location_menu = LocationMenu.create! valid_attributes
      get :show, {:id => location_menu.to_param}, valid_session
      assigns(:location_menu).should eq(location_menu)
    end
  end

  describe "GET new" do
    it "assigns a new location_menu as @location_menu" do
      get :new, {}, valid_session
      assigns(:location_menu).should be_a_new(LocationMenu)
    end
  end

  describe "GET edit" do
    it "assigns the requested location_menu as @location_menu" do
      location_menu = LocationMenu.create! valid_attributes
      get :edit, {:id => location_menu.to_param}, valid_session
      assigns(:location_menu).should eq(location_menu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LocationMenu" do
        expect {
          post :create, {:location_menu => valid_attributes}, valid_session
        }.to change(LocationMenu, :count).by(1)
      end

      it "assigns a newly created location_menu as @location_menu" do
        post :create, {:location_menu => valid_attributes}, valid_session
        assigns(:location_menu).should be_a(LocationMenu)
        assigns(:location_menu).should be_persisted
      end

      it "redirects to the created location_menu" do
        post :create, {:location_menu => valid_attributes}, valid_session
        response.should redirect_to(LocationMenu.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved location_menu as @location_menu" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocationMenu.any_instance.stub(:save).and_return(false)
        post :create, {:location_menu => {  }}, valid_session
        assigns(:location_menu).should be_a_new(LocationMenu)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LocationMenu.any_instance.stub(:save).and_return(false)
        post :create, {:location_menu => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested location_menu" do
        location_menu = LocationMenu.create! valid_attributes
        # Assuming there are no other location_menus in the database, this
        # specifies that the LocationMenu created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LocationMenu.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => location_menu.to_param, :location_menu => { "these" => "params" }}, valid_session
      end

      it "assigns the requested location_menu as @location_menu" do
        location_menu = LocationMenu.create! valid_attributes
        put :update, {:id => location_menu.to_param, :location_menu => valid_attributes}, valid_session
        assigns(:location_menu).should eq(location_menu)
      end

      it "redirects to the location_menu" do
        location_menu = LocationMenu.create! valid_attributes
        put :update, {:id => location_menu.to_param, :location_menu => valid_attributes}, valid_session
        response.should redirect_to(location_menu)
      end
    end

    describe "with invalid params" do
      it "assigns the location_menu as @location_menu" do
        location_menu = LocationMenu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocationMenu.any_instance.stub(:save).and_return(false)
        put :update, {:id => location_menu.to_param, :location_menu => {  }}, valid_session
        assigns(:location_menu).should eq(location_menu)
      end

      it "re-renders the 'edit' template" do
        location_menu = LocationMenu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LocationMenu.any_instance.stub(:save).and_return(false)
        put :update, {:id => location_menu.to_param, :location_menu => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested location_menu" do
      location_menu = LocationMenu.create! valid_attributes
      expect {
        delete :destroy, {:id => location_menu.to_param}, valid_session
      }.to change(LocationMenu, :count).by(-1)
    end

    it "redirects to the location_menus list" do
      location_menu = LocationMenu.create! valid_attributes
      delete :destroy, {:id => location_menu.to_param}, valid_session
      response.should redirect_to(location_menus_url)
    end
  end

end
