require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RealEstateListingsController do

  # This should return the minimal set of attributes required to create a valid
  # RealEstateListing. As you add validations to RealEstateListing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RealEstateListingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all real_estate_listings as @real_estate_listings" do
      real_estate_listing = RealEstateListing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:real_estate_listings).should eq([real_estate_listing])
    end
  end

  describe "GET show" do
    it "assigns the requested real_estate_listing as @real_estate_listing" do
      real_estate_listing = RealEstateListing.create! valid_attributes
      get :show, {:id => real_estate_listing.to_param}, valid_session
      assigns(:real_estate_listing).should eq(real_estate_listing)
    end
  end

  describe "GET new" do
    it "assigns a new real_estate_listing as @real_estate_listing" do
      get :new, {}, valid_session
      assigns(:real_estate_listing).should be_a_new(RealEstateListing)
    end
  end

  describe "GET edit" do
    it "assigns the requested real_estate_listing as @real_estate_listing" do
      real_estate_listing = RealEstateListing.create! valid_attributes
      get :edit, {:id => real_estate_listing.to_param}, valid_session
      assigns(:real_estate_listing).should eq(real_estate_listing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RealEstateListing" do
        expect {
          post :create, {:real_estate_listing => valid_attributes}, valid_session
        }.to change(RealEstateListing, :count).by(1)
      end

      it "assigns a newly created real_estate_listing as @real_estate_listing" do
        post :create, {:real_estate_listing => valid_attributes}, valid_session
        assigns(:real_estate_listing).should be_a(RealEstateListing)
        assigns(:real_estate_listing).should be_persisted
      end

      it "redirects to the created real_estate_listing" do
        post :create, {:real_estate_listing => valid_attributes}, valid_session
        response.should redirect_to(RealEstateListing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved real_estate_listing as @real_estate_listing" do
        # Trigger the behavior that occurs when invalid params are submitted
        RealEstateListing.any_instance.stub(:save).and_return(false)
        post :create, {:real_estate_listing => {  }}, valid_session
        assigns(:real_estate_listing).should be_a_new(RealEstateListing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RealEstateListing.any_instance.stub(:save).and_return(false)
        post :create, {:real_estate_listing => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested real_estate_listing" do
        real_estate_listing = RealEstateListing.create! valid_attributes
        # Assuming there are no other real_estate_listings in the database, this
        # specifies that the RealEstateListing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RealEstateListing.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => real_estate_listing.to_param, :real_estate_listing => { "these" => "params" }}, valid_session
      end

      it "assigns the requested real_estate_listing as @real_estate_listing" do
        real_estate_listing = RealEstateListing.create! valid_attributes
        put :update, {:id => real_estate_listing.to_param, :real_estate_listing => valid_attributes}, valid_session
        assigns(:real_estate_listing).should eq(real_estate_listing)
      end

      it "redirects to the real_estate_listing" do
        real_estate_listing = RealEstateListing.create! valid_attributes
        put :update, {:id => real_estate_listing.to_param, :real_estate_listing => valid_attributes}, valid_session
        response.should redirect_to(real_estate_listing)
      end
    end

    describe "with invalid params" do
      it "assigns the real_estate_listing as @real_estate_listing" do
        real_estate_listing = RealEstateListing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RealEstateListing.any_instance.stub(:save).and_return(false)
        put :update, {:id => real_estate_listing.to_param, :real_estate_listing => {  }}, valid_session
        assigns(:real_estate_listing).should eq(real_estate_listing)
      end

      it "re-renders the 'edit' template" do
        real_estate_listing = RealEstateListing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RealEstateListing.any_instance.stub(:save).and_return(false)
        put :update, {:id => real_estate_listing.to_param, :real_estate_listing => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested real_estate_listing" do
      real_estate_listing = RealEstateListing.create! valid_attributes
      expect {
        delete :destroy, {:id => real_estate_listing.to_param}, valid_session
      }.to change(RealEstateListing, :count).by(-1)
    end

    it "redirects to the real_estate_listings list" do
      real_estate_listing = RealEstateListing.create! valid_attributes
      delete :destroy, {:id => real_estate_listing.to_param}, valid_session
      response.should redirect_to(real_estate_listings_url)
    end
  end

end
